services:
  controleportarias:
    build: .
    image: controleportarias:latest
    container_name: controleportarias
    ports:
      - "8000:80"
    depends_on:
      - mariadb
    networks:
      - controleportarias-network
    volumes:
      - ./:/var/www/html
    environment:
      HOME: /tmp
    user: "${UID:-1000}:${GID:-1000}"

  mariadb:
    image: mariadb:11
    container_name: controleportarias_mariadb
    restart: always
    environment:
      MYSQL_DATABASE: controleportarias
      MYSQL_USER: controleportarias
      MYSQL_PASSWORD: controleportarias
      MYSQL_ROOT_PASSWORD: controleportarias
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - controleportarias-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: controleportarias_phpmyadmin
    restart: always
    depends_on:
      - mariadb
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: controleportarias
    networks:
      - controleportarias-network

  selenium:
    image: selenium/standalone-chrome
    container_name: controleportarias_selenium
    ports:
      - "7900:7900"
    networks:
      - controleportarias-network
    shm_size: 2gb

  # No /etc/hosts do seu computador colocar a linha `127.0.0.1 auth.local`
  # particularidades do protocolo oAuth1 usado na USP
  senhaunica-faker:
    image: uspdev/senhaunica-faker
    container_name: controleportarias_senhaunica-faker
    ports:
      - "3141:3141"
    environment:
          - APP_URL=http://auth.local:3141
    networks:
      controleportarias-network:
        aliases:
          - auth.local

  mailpit:
    image: axllent/mailpit:latest
    container_name: controleportarias_mailpit
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Interface Web
    networks:
      - controleportarias-network

networks:
  controleportarias-network:

volumes:
  mariadb_data:
